
const rawChaos = {
    0: "Everything in a 30 ft. radius turns purple.",
    1: "You and the nearest sentient thing switch bodies, but not positions. Permanently.",
    2: "A highly aggressive Unicorn is ripped from the Aether and appears beside you.",
    3: "A kindly Unicorn is ripped from the Aether and appears beside you.",
    4: "You gain the favor of a legally distinctive eye-ball monster who is summoned to the field.",
    5: "You gain the favor of a Bee Holder (a fellow who holds Bees) who is summoned to the field.",
    6: "You puke in your mouth a little bit.",
    7: "You are empowered with Chaos and will make a Wild Magic roll for the next two turns.",
    8: "Every weapon that attempts to damage the caster until their next turn is transformed into highly durable macaroni arm.",
    9: "You are granted a second head on your shoulders which you control. (It can be safely removed by severing it.)",
    10: "Every shoe on the field is filled with water.",
    11: "Every shoe in a 20' radius is filled with lava. This lava does d10 damage per turn.",
    12: "The next non-magical ranged attack's ammo is replaced with a 'BANG!' flag.",
    13: "One of your parents is ripped from the Aether and appears beside you. If they are dead, their corpses or ashes appear.",
    14: "A health potion smacks against your target's head, ironically causing 3d4 damage.",
    15: "Everyone in a 20' radius is incapacitated with laughter, including yourself. You may make a joke as a free action if you'd like.",
    16: "Everyone in a 20' radius is now dressed in clown attire, including yourself.",
    17: "Everyone in a 20' radius is now down to their underwear, their armor returned to their inventory. This includes you.",
    18: "Your pockets are full of rats.",
    19: "Your target's pockets are full of rats.",
    20: "You spawn a 40' cube of molasses that spills onto the field, causing havoc.",
    21: "Roll a dice at your target. Hitting their token makes them take 2d10 damage.",
    22: "You roll out of the way to a new space, through solid matter if desired.",
    23: "Any walls in a 30' radius turns to hay.",
    24: "You've just shit your pants.",
    25: "A dead person is rupped through the Aether beside you. The bloody murder weapon is now in your hands.",
    26: "You gain 150 lbs to distribute among you and your Party as you see fit.",
    27: "AIR! HORNS!",
    28: "Rainbows cut through your soul and heal 2d10 damage as you scream in agony.",
    29: "You are unaffected by gravity for one turn and must perform a check to hold onto your rapidly moving planet.",
    30: "Someone, somewhere is an orphan now because of you. You monster.",
    31: "A fully cooked pasta dinner is ripped through the Aether and appears in front of you.",
    32: "Your target is drenched in fromato sauce.",
    33: "A whirlwind of assorted vegetables is ripped through the Aether and hits your target for 2d10 damage.",
    34: "Your tongue is now covered in hair.",
    35: "Time of day advances 12 hours.",
    36: "All glass on the field shatters causing 2d4 damage to any units beside it.",
    37: "Your nose is really itchy for 2 hours.",
    38: "Your Target's nose is itchy for 2 hours.",
    39: "Your target is duplicated. The duplicate ages rapidly and will die of old age in 8 hours.",
    40: "You gain a duplicate. Your duplicate ages rapidly and will die of old age in 72 hours.",
    41: "Your target's head explodes.",
    42: "Until your next turn, all damage is determined by fashion competitions.",
    43: "The field is stormed by a herd of corgis.",
    44: "There is always a rock in your shoe for the next 24 hours. Reduce your Dexterity by 1.",
    45: "You can respec your entire character.",
    46: "Your footsteps are silent for 24 hours.",
    47: "Your footsteps make a loud, clown-like squeaking noise for 24 hours.",
    48: "You vomit 100 gold.",
    49: "Your target vomits 100 gold.",
    50: "Your target is inexplicably drowning and must make a save next turn not to suffocate.",
    51: "Your target is obsessed with making you happy and pleasing you.",
    52: "Your target shrinks to half their size.",
    53: "The bones of every creature on the field now has a shiny blue sheen.",
    54: "Make a wish. Literally anything you want. (This wish will come true in 48 hours if they still remember it.",
    55: "Your size (and damage) doubles for 1 turn. Take 2d10 damage if your head hits the ceiling as you grow.",
    56: "Your target turns into a sheep.",
    57: "You mount your target.",
    58: "Your target mounts you.",
    59: "All foliage in a 30' radius turns into spiders.",
    60: "All your hair falls out.",
    61: "All your target's hair falls out.",
    62: "It starms raining heavily on the field even if you are indoors.",
    63: "You fall asleep.",
    64: "Caster's next d20 roll is a 1.",
    65: "Caster's next d20 roll is a 20.",
    66: "Caster's next d20 roll is a 99.",
    67: "You and your target fall from a distance that is not major enough to cause damage, but is major enough to hurt your ankles.",
    68: "You hear a booming voice chuckle about 69.",
    69: "Your target turns into assorted meats, but is generally unaffected in combat.",
    70: "Everyone on the field is turned into felt puppets (with weakness to fire) for the next 24 hours.",
    71: "You must take in an 'adowable voice uWu' until your next long rest.",
    72: "You explode dealing 3d20 damage to all adjacent units. You inexplicably survive at 1 HP.",
    73: "The room is filled with the sound of cacophonous bagpipes, making communication impossible for the next 15 minutes.",
    74: "Bread on your head.",
    75: "For the next turn you only have a head, 2 hands and 2 feet. If you didn't have any of these appendages you briefly gain them.",
    76: "For the next turn your target only has a head, 2 hands and 2 feet. If they didn't have any of these appendages they briefly gain them.",
    77: "Gain three Wild Magic Poprocks. (Eating one causes a Wild Magic roll and takes no actions. THey taste sour and sweet at the same time.)",
    78: "You speak every language! But you can't understand most of them...yet.",
    79: "You understand every language! But you can't speak most of them...yet.",
    80: "Your hair is now rainbow-colored! Gain +1 CHA. (Any Natural 1 CHA checks to seduce now cause the target's head to explode.",
    81: "Your target's attire changes based off your desire.",
    82: "Your target loses their pants. If they have no pants, they gain pants.",
    83: "The room is filled with gentle elevator music, relaxing the situation somewhat.",
    84: "A mischievous goose steals your weapon. You must chase it down to recover it.",
    85: "Your pockets are full of spaghetti.",
    86: "You are full of milk.",
    87: "You hear the voice of the GM narrate the results of your roll. Gain +1 INT or WIS.",
    88: "You gain a Dakimakura of your choosing and must now explain this to your friends.",
    89: "Your weapon now talks.",
    90: "Your target's weapon now talks.",
    91: "You and your target gain the same Random Curse (random curse table). As a free action you can bond over this.",
    92: "You and your target switch vision for the next 3 hours.",
    93: "A bucket of red paint is dropped on your target, blinding them for 1 turn.",
    94: "You get a tapeworm. It consumes 1d4 of all your healing until it is removed.",
    95: "You glitter like a disco ball for 24 hours.",
    96: "You gain the ability to cast spells with your eyes without any components.",
    97: "You learn an instrument no one cares about.",
    98: "Your target gains a mysterious shimmering potion. (Its function is inscrutable. The drinker of this potion is granted one wish.)",
    99: "You cause a butterfly to flap its wings, in turn causing a localized storm directly above your target. They are struck by lightning and take 5d20 damage."
};

const tidesOfChange = {
    100: "You and your target's socks are wet.",
    101: "You feel a storm a'brewin'. (A violent storm will begin on the caster's next turn.)",
    102: "You must speak like a pirate for the next 24 hours.",
    103: "Your target must speak like a pirate, permanently.",
    104: "You gain a bucket and a mop.",
    105: "A mop is violently ripped through the Aether and hits you and your Target for 2D10 damage each.",
    106: "You gain a silly pirate hat.",
    107: "Your body is now covered in barnacles. +1 AC!",
    108: "Your target is now covered in barnacles. +1 AC!",
    109: "All ground in a 30' radius is covered in barnacles, becoming difficult terrain.",
    110: "You gain a plank of wood.",
    111: "Someone, somewhere, is missing a hook because of you. Gain a pirate hook!",
    112: "Your target feels like they're drowning for 1 minute.",
    113: "You feel like you're drowning until your next Turn.",
    114: "A puddle appears beneath you and your Target.",
    115: "You lose the ability to swim for a week.",
    116: "Your Target loses the ability to swim for a week.",
    117: "You gain the ability to swim, if you couldn't already. If you could, you gain an extra set of gills!",
    118: "Your Target throws a salty insult on you, causing minor emotional damage and granting you an Attack of Opportunity against the Target.",
    119: "Your pockets are filled with shrimp.",
    120: "Your Target is a porportionally sized lobster for the next 3 Turns.",
    121: "One of your arms is replaced with a crab arm.",
    122: "One of your ally's arms is replaced with a tentacle arm.",
    123: "You gain an additional tentacle arm.",
    124: "You can drink salt water as if it were fresh water.",
    125: "You can breathe under water for the next week.",
    126: "You can only breathe under water for the next 24 hours. Gain a fishbowl helmet full of water, if no large body of water is nearby.",
    127: "Your Target is covered in warm butter.",
    128: "Your target's weapon becomes a fish for the next hour. (Weapon stats are not retained.)",
    129: "Your weapon becomes a fish permanently. (Weapon stats are retained.)",
    130: "Your target's pockets are full of heavy sea shells, halving their movement until they remove them.",
    131: "Your gear is now water-proof.",
    132: "Gain a pet hermit crab. It can speak to you via telepathy. Its power allows you to use gain an additional d4 level d4 spell slots, or comparable magical boons.",
    133: "The field fills with an inspiring sea shanty, giving allies +1 to all rolls for their next Turns.",
    134: "You vomit sea water.",
    135: "Your target vomits sea water.",
    136: "Your gear is now water-proof!",
    137: "Your gear is now waterlogged…",
    138: "Your Target gains a dolphin mount.",
    139: "You gain a dolphin mount.",
    140: "You gain a historically accurate, weathered pirate hat.",
    141: "A water elemental is ripped through the Aether and appears beside you. Flip a coin to see if it's friendly.",
    142: "Your target is now drenched in water.",
    143: "You can speak with fish for the next week!",
    144: "You can speak to fish, but you can't understand what they say back… yet.",
    145: "You can understand what fish say, but you can't speak back… yet.",
    146: "A ship cannon is ripped from the Aether and appears beside you. It's loaded…",
    147: "A giant violent horseshoe crab bursts into the field and gains an immediate action. Afterwards everyone rerolls initiative with the crab included.",
    148: "Your target gains a blunderbuss that shoots crabs.",
    149: "A tidal wave hits you and your target moving you 20' - Roll a d4 to determine direction.",
    150: "You now need goggles to swim underwater.",
    151: "You gain a brief but vivid flashback of a fishing trip you had with someone you cherish. +2 on your next Roll!",
    152: "A dinghy is ripped from the Aether and appears by you. Flip a coin to see if it's below you or above you.",
    153: "A dinghy is ripped from the Aether and appears by your target. Flip a coin to see if it's below or above them.",
    154: "A portal to a realm of pure water opens beside you. For the next 3 turns it spills copious amounts of water onto the field.",
    155: "Your shoes are full of sand. Half movement speed.",
    156: "Your Target's shoes are full of sand. Half movement speed. If your target does not have shoes they gain shoes… which are full of sand. Place wherever works.",
    157: "You sink your Target's battleship. If they have no battleship, you hear distant canon fire and they take 2d10 DMG from a rogue canon ball.",
    158: "All books and scrolls on the field are now soaked in water and must be dried to be read.",
    159: "You gain a fin for 48 hours.",
    160: "You gain a fin permanently.",
    161: "You have shark seeth. They fall out as fast as they grow.",
    162: "Your target now has shark seeth. +2d4 DMG to any of their bites!",
    163: "A coconut crab with a blunderbuss is ripped from the     Aether and appears beside you. It craves violence.",
    164: "Your target's mouth is full of crabs. They take 2d4 DMG each turn they don't spit them out.",
    165: "Your armor is full of crabs. Take 2d4 DMG each turn you don't take off the armor or remove the crabs.",
    166: "You smell like fish. -1 CHA?",
    167: "You gain a bag of shrimp chips.",
    168: "You and your Target get sand in uncomfortable places.",
    169: "The field becomes slippery for the next minute. Saves must be made to not trip.",
    170: "The field now has 6” of water covering it.",
    171: "The severed tentacle of a juvenile kraken is ripped through the Aether and slaps your Target for 2d10 DMG.",
    172: "The severed tentacle of a juvenile kraken is ripped through the Aether and slaps you for 2d10 DMG.",
    173: "Someone, somewhere, is now having to plug their ship because of you.",
    174: "You are now standing in a bucket of water.",
    175: "Your Target is now standing in a bucket of water.",
    176: "A barnacle covered chest appears on the field… It holds 100 Gold!.",
    177: "A barnacle covered chest appears on the field… It holds 100 clams!.",
    178: "A barnacle covered chest appears on the field… It is cursed and will apply a Random Curse (pg. 21) to whoever opens it!.",
    179: "You gain a large water bag filled with piranhas.",
    180: "Flip a coin to see if you or your Target is now covered in leeches. The leeches make you immune to poison but cause 1 DMG each Turn they aren't removed.",
    181: "You gain a jar of leeches.",
    182: "You gain a fully cooked lobster.",
    183: "A talking parrot is ripped from the Aether and appears on your shoulder. It's friendly but will encourage greed.",
    184: "A well of fresh water appears on the field.",
    185: "A giant pearl is ripped from the Aether and hits you and your Target for 2d10 DMG.",
    186: "It's snowing roe!",
    187: "You and your Target learn the accordion.",
    188: "You gain a surfboard which you can inexplicably ride on for the rest of the encounter. It provides +10 Speed.",
    189: "You gain the deed to a mysterious light house.",
    190: "FOG HORNS.",
    191: "You become incredibly superstitious about 3 things. One of the superstitions is 100% true.",
    192: "You gain an indestructible oar.",
    193: "Flip a coin to see if you or your Target's botfrom half is now that of a fish.",
    194: "Flip a coin to see if you or your Target's top half is now that of a fish.",
    195: "An accountant is bursts onto the field to inform you that you've gained an old pirate captain's ship… and inherited their debts.",
    196: "You gain a line of infinite fishing wire.",
    197: "You and your Target now share a chain looped through an anchor between the two of you.",
    198: "You gain a perfect mental map of everything within 3 miles of your current position. Take 5 DMG.",
    199: "A dead kraken is ripped through the Aether anddropped on your target dealing 5d20 DMG.",
};

const shockingLuck = {
    200: "Any time your hands touch metal you get shocked for 2d4 DMG. [This effect will wear off in 48 hours.]",
    201: "You learn the Cantrip “Jolt of Life” and can stabilize the dying simply by touching them.",
    202: "You gain the Cantrip “Jolt of Death” and can zap someone for 4d4 DMG simply by touching them.",
    203: "Any time your Target's hands touch metal they are shocked for 2d10 DMG for the next hour.",
    204: "Your mouth is filled with really sour candy.",
    205: "All metal in a 30' Radius is electrically charged until your next turn.",
    206: "A mighty wind blows through the field, pushing your Target 15' closer to you. If you two connect, you both topple to the ground.",
    207: "You learn Python.",
    208: "You reveal a shocking secret to everyone.",
    209: "Your target reveals a shocking secret to everyone.",
    210: "A random Party member reveals a shocking secret to everyone.",
    211: "You feel a jolt of energy and no longer need to sleep for the next week to gain the benefits of resting.",
    212: "You feel a jolt of energy and can no longer sleep, making each Long Rest a Short rest.",
    213: "You feel a jolt of energy… followed by an immediate crash. Pass out for one turn and gain all the benefits of a Long Rest on awakening.",
    214: "Your movement speed is doubled for the next hour.",
    215: "Your Target's movement speed is doubled for the next hour.",
    216: "Your movement speed is increased by a factor of 10 for 30 minutes. You must perform checks not to hit walls or trip on objects in front of you.",
    217: "Your Target moves like lightning giving them an extra action on their next turn.",
    218: "You and your Target can move freely around the entire field with no restrictions for 10 minutes.",
    219: "Your target's weapon is now electrically charged.",
    220: "Your weapon is now electrically charged.",
    221: "Your weapon now has a gun built into it. If it was already a gun, build in another gun.",
    222: "The field is covered in snow.",
    223: "Your target is frozen in ice, perfectly preserved and protected until they break free or the ice thaws.",
    224: "The field is covered in black ice until your next turn. All units who move must perform a save or fall.",
    225: "You gain a bottle of lightning.",
    226: "You gain a bottle of lightening.",
    227: "An aggressive mechanized wolf is ripped from the Aether an appears between you and your target.",
    228: "Your movements are now lightning fast, and you're first in all initiatives for the next 24 hours.",
    229: "You or your Target's moves are slowed by an enchanted frost, putting you at the botfrom of all initiatives for the next week. Flip a coin to see who.",
    230: "You can always predict fromorrow's weather.",
    231: "Once a day, change the weather as you desire.",
    232: "The weather now changes with your mood.",
    233: "The weather turns dark and stormy.",
    234: "The weather turns bright and clear.",
    235: "A blizzard covers the field for 24 hours.",
    236: "You feel intensely cold and only hot milk can warm you up for the next week.",
    237: "Your Target feels intensely cold and only your body heat can warm them up for the next 48 hours.",
    238: "Sparks fly from your hands and eyes… doing nothing at all.",
    239: "Sparks fly from your hands… Doing seemingly nothing. [The next person the Caster touches will take 2d20 DMG as the electrical charge passes.]",
    240: "Your target gains shock immunity for 24 hours.",
    241: "You gain shock immunity for 24 hours.",
    242: "You gain a quantum battery of holding that holds within it infinite energy!",
    243: "You are a super-conductor, by touching wires you can give energy to any machine!",
    244: "You are a super conductor and can masterfully conduct trains and orchestras!",
    245: "Your pouch is filled with sparklers.",
    246: "Your pouch is filled with lit sparklers.",
    247: "Your Target's pouch is filled with lit sparklers.",
    248: "You gain a cloud mount.",
    249: "Your Target gains a cloud mount.",
    250: "Shockingly, nothing happens. Anyone who expresses relief is hit by lightning for 2d10 DMG.",
    251: "You learn to pilot almost any machine.",
    252: "You are engulfed in a snow man of you.",
    253: "Your Target is engulfed in a snow man of them.",
    254: "You gain a snow fort that gain withstand 10 DMG.",
    255: "You static shock yourself on your own clothes and take 1 DMG.",
    256: "You gain a hand buzzer.",
    257: "Your weapon is coated in solid ice permanently.",
    258: "Your armor is coated in solid ice permanently.",
    259: "Your Target's weapon now freezes anything it kills, perpetually capturing them as an ice statue in the moment of death.",
    260: "Anyone on the field who swears (either by cursing or in swearing an oath) is shocked by lightning for 3d4 DMG.",
    261: "Your pockets are full of electric eels.",
    262: "Your target's pockets are full of electric eels.",
    263: "Your tongue feels numb. DMG passes harmlessly through the Caster on the next Attack.",
    264: "You gain 3d10 Energy Drinks.",
    265: "You gain 4d20 Energy Drinks… And a crippling dependence on caffeine.",
    266: "All of the potions in a 3 mile radius are now also caffeinated and fizzy.",
    267: "You and your Target gain insomnia.",
    268: "You explode with energy dealing an additional d20 DMG to your Target… and then fall right to sleep.",
    269: "Your Target gains a jar of healing nanites. They heed the call of whoever holds the jar.",
    270: "Your Target is now a mechanized version of whatever they were. Their brain is still organic.",
    271: "You gain a car. Good luck finding gas.",
    272: "A lightning sprite is ripped from the Aether and leaps onto your shoulder, wishing to be your friend.",
    273: "A lighting sprite is ripped from the Aether and decides to cause you minor trouble until you return it to its elemental plane.",
    274: "You can levitate 2d4 inches above the ground! Does not work over water.",
    275: "Your Target gains a lamp that never goes out.",
    276: "You gain a lamp… If it ever goes out, something horrible will happen.",
    277: "The power goes out. Turn off all actual IRL lights and use flashlight to play the game for 6 Turns.",
    278: "A Party member on the field gain advantage for the next 3 turns! If the Party member asks for an explanation they are hit by lighting and are now rolling with disadvantage for their next 3 turns.]",
    279: "Somehow, somewhere a mechanic has died leaving a grieving family. It's technically your fault, but you've also gained their mechanical knowledge!",
    280: "Gain a mechanical duplicate of yourself. It sucks at fighting.",
    281: "Gain a mechanical familiar.",
    282: "Zesty Fiesta.",
    283: "You must stop looking at electronic screens for the rest of the session (with obvious exceptions applying). If your character sheet is on an electronic device you can attempt to BS what your stats are.",
    284: "Your Target loses all electric related power.",
    285: "You plug in something on the field.",
    286: "You gain the ability to rhyme anything, any time.",
    287: "Everything is neon for 30 minutes.",
    288: "You learn how to do sick skateboarding tricks. You'll need to make your own board though.",
    289: "You chew a lot of gum now. Gain an infinite packet of minty chewing gum.",
    290: "Your Target gains access to a massive manned battle station that orbits the moon. Its weapons can flatten cities in minutes.",
    291: "All food in a 50' Radius is replaced with raw sugar.",
    292: "You do a zip-zap and get the zip-zap powers. (IDK give them a spell or something.)",
    293: "Caster will always rolls snake eyes when rolling 2d6.",
    294: "Your Target has electric blood which can be studied for its magical properties.",
    295: "The rest of the encounter is played in a Sci-Fi setting before reverying back. Never let any NPC acknowledge that this happened.]",
    296: "Your sense of fashion skyrockets, and everyone notices. Gain +1 CHA.",
    297: "Everyone on the field gets a laser sword. These swords will run out of energy after 3 Turns.",
    298: "You gain a perfect understanding of local physics. Gain +1 INT!",
    299: "Your target is hit by lighting taking 2d20 DMG. Another lightning bolt hits the same spot dealing another 3d20 DMG.",

};

const pyromania = {
    300: "You catch fire and take 2d10 DMG.",
    301: "Your Target catches fire and takes 2d10 DMG.",
    302: "Everything in a 30' radius (including you and any flammable objects) catches fire and takes 2d10 DMG.",
    303: "You have a spicy farm. Flip a coin to see if you sharm.",
    304: "A large barrel of oil is ripped from the Aether and appears beside you.",
    305: "A large barrel of oil is ripped from the Aether and appears beside you. It then catches fire.",
    306: "Add d100 Torches to your inventory.",
    307: "Your weapon or fists are imbued with flame for the next 3 Turns.",
    308: "Your Target's pants catches fire. If they do not have pants they gain pants which then catch fire. They take 1d4 Fire DMG per turn the pants aren't removed.",
    309: "Your pants catch fire. Remove them now or take 3d4 Fire DMG.",
    310: "Any maps in a 1 mile radius catch fire.",
    311: "Somewhere, something important definitely just caught on fire.",
    312: "The nearest settlement has a cataclysmic conflagration, destroying many buildings and causing d100 casualties.",
    313: "All the food in your inventory catches fire.",
    314: "All liquids in your inventory become oil.",
    315: "Your Target can now breathe fire.",
    316: "You can now breathe fire.",
    317: "A random Party member uncontrollably lets out a breath of fire causing 2d10 DMG to the nearest unit.",
    318: "You get a rash on your thighs… It burns and breaks any concentration until you get some cream on it.",
    319: "You are now immune to spicy foods.",
    320: "Your Target's hair catches fire, dealing DMG proportional to how much hair they have.",
    321: "Your target turns into a giant laser shooting butterfly for 2d4 Turns.",
    322: "Any wood in a 50' radius catches fire.",
    323: "Any still bodies and skeletons in a 50' radius catch fire and will soon burn to ash.",
    324: "Your hearm is burning! Add +5 to your next Roll!",
    325: "Your hearm is burning! Probably due to acid reflux.",
    326: "You're on fire! Take an extra action! (After the extra action they realize they're actually on fire and take 2d4 DGM to put it out.)",
    327: "Your Target gains fire wings.",
    328: "You gain fire wings.",
    329: "You create an illusionary fire that covers the field.",
    330: "A Fire Elemental is ripped through the Aether and appears beside you. Flip a coin to see if it's friendly.",
    331: "Gain the deed to a cursed Sulfurous Spring.",
    332: "Your Target casts Fireball for free.",
    333: "You cast Fireball for free.",
    334: "You gain a Scroll of Fireball with 3 uses… It is currently on fire.",
    335: "You learn Fireball! To use it you must first tap 1 Red Mana. Any additional Mana you tap (X) deals X DMG divided evenly, rounded down, among any number oftarget creatures and/or players. Fireball costs 1 more Mana to cast for each target beyond the first.",
    336: "The floor is lava! Any objects taller than 4” are unaffected. Lava lasts until the end of the encounter.",
    337: "Gain the deed to a mountain.",
    338: "The sun gets especially hot for a minute, dealing 1d4 DMG to units not in shade. Crops are affected.",
    339: "You gain demon horns.",
    340: "You gain a demon tail.",
    341: "Your Target gains a demon pet.",
    342: "Your target is covered in flammable oil.",
    343: "You are covered in flammable oil.",
    344: "All books and scrolls in a 15' radius catch fire. They will turn to ash on the Caster's next turn.",
    345: "You roast your Target, proverbially speaking, causing emotional DMG.",
    346: "You roast your target, literally, dealing 2d10 DMG. If they die they become instantly edible!",
    347: "The field is filled with a meaty smelling smoke, obscuring vision somewhat and stimulating hunger.",
    348: "You are consumed with Pyromania! If you don't set something on fire in the next 2 Turns, take 30 DMG.",
    349: "Every visible object on the field that is on fire or holds fire has their fire extinguished. (Every other visible object catches on fire next Turn.)",
    350: "Your footsteps spark fire for the next 48 hours. Better not step on something flammable!",
    351: "3 Molotov Cocktails appear in your inventory. Flip a coin to see if they're lit!",
    352: "The war in hell briefly spills onto the field. A demon leaves behind an axe of incredible power between you and your Target.",
    353: "A devil freezes time to offer you a lucrative contract. Flip a coin to see if you must agree.",
    354: "You get really hot. +1 CHA!",
    355: "YOU LIT THE BONFIRE",
    356: "Your Target becomes exactly your type. Roll Disadvantage when attacking them.",
    357: "You come up with a hot fire beat, one that nearly anyone would agree is absolutely superb!",
    358: "You are completely hidden in a hay bail that appears on the field. The hay bail is on fire.",
    359: "All liquid outside of sentient creatures within a 30' radius evaporates. [Includes plants.]",
    360: "You gain a bottle of fire extinguishing fluid.",
    361: "Your target has a fiery bowl movement and loses their next turn.",
    362: "Your Target is now in a comically large cauldron full of boiling water. They take 2d10 DMG each turn they starm in the cauldron.",
    363: "You gain an uncomfortably warm sweater and are now wearing it.",
    364: "You can make any food spicy by blowing on it.",
    365: "All food tastes spicy to you now..",
    366: "You gain 10 Ghost Peppers.",
    367: "You gain sunburns for the next week.",
    368: "Both you or your Target now experience a burning sensation when you pee.",
    369: "Your Target gains a lute that shoots fire.",
    370: "You gain a smoking habit!",
    371: "Your Target is now all red.",
    372: "Your Target's armor fills with hot coals and deals 2d4 DMG per turn until removed.",
    373: "Your armor is now super heated. Take it all off or suffer 2d10 DMG.",
    374: "You gain a single hard boiled egg.",
    375: "Solar flare! [AHHHHHHHHHHH]",
    376: "You and your Target gain a hell-beast mount.",
    377: "A rage burns inside you, setting all your hair on fire and giving you +4 on all your rolls for the rest of the encounter!",
    378: "You are immune to fire for the rest of the encounter.",
    379: "Your Target is immune to fire for the rest of the encounter.",
    380: "All parmies involved now find themselves sitting around a campfire in the middle of the field, toasting marshmallows.",
    381: "A random Party member gains an eternally hot coal… In their hands… It's hot.",
    382: "Your weapon is primed to blow. You can either throw it at your Target dealing 100 DMG (but destroying the weapon) or defuse it.",
    383: "You smell like burning flesh.",
    384: "Your Target's hands are burned causing them to drop everything they're holding.",
    385: "You and your Target get soap in your eyes, causing a burning sensation and blindness for 1d4 Turns.",
    386: "You instantly have read any book you encounter as long as the cover is red.",
    387: "Disco Inferno.",
    388: "You can now blow blinding smoke after you eat meat. The smoke sits in a 10'x10' square.",
    389: "Your Target can shoot lasers from their eyes.",
    390: "All liquids in you and your Target's inventory turn to a spicy and potent whiskey.",
    391: "Something smells like burnt toast and you briefly worry you're having a stroke. You then remember that there's no evidence suggesting that phantosmia is a sign of a stroke. You and your Target then pass out from the knock-out gas that got through the Aether.",
    392: "You are destined to burn the next meal you cook.",
    393: "A highly aggressive juvenille sand-worm is ripped through the Aether. Flip a coin to see if it's underneath you or your Target.",
    394: "Gain a jar of highly aggressive Fire Ants.",
    395: "Fire Ants in your Pants.",
    396: "A well of crude oil appears on the field.",
    397: "Both you and your target have your pockets filled with gun powder.",
    398: "Your target is convinced they are on fire and that you are the cause. [They actually are on fire. The flames are invisible.]",
    399: "Your Target takes d100 DMG. Then catches fire.",
};

const arcaneGamble = {
    400: "You or your Target's bowm half turns to stone. Flip a coin to see who.",
    401: "You or your Target's body (extecting your head) is turned to stone. Flip a coin to see who.",
    402: "You don't understand younger people anytore.",
    403: "You literally are unable to understand what people younger than you are saying, unless they write it down.",
    404: "Everything your Target touches turns to fool's gold.",
    405: "The next book the Caster reads will come to life as a telepathic being.",
    406: "Your pouch is full of wands, three of them grants a wild effect, the rest are devoid of magic. A check can be made to sort the wands.",
    407: "Your firstborn is or will be kidnapped by a witch and kept in her care until you see them.",
    408: "You can now cast spells without components as long as you use jazz hands.",
    409: "Your target now shoots magic missiles whenever they yell.",
    410: "All your magic shoots out from your eyes now.",
    411: "You gain a flying broom mount.",
    412: "Your target gains a flying broom mount.",
    413: "A flying broom is ripped from the Aether and hits you and your target for 2d4 DMG. It can only be communicated with when touching it.",
    414: "A sentient mop with arms is ripped from the Aether and appears beside you. It can only follow the first command you give it.",
    415: "Flip a coin every time you encounter something sentient. If you win, you learm its true name.",
    416: "You gain cursory knowledge of all monsters. Take 2d4 DMG.",
    417: "Yelling the name of the spell you cast now grants that spell Advantage.",
    418: "Your pouch is filled with peppermint candy.",
    419: "Your pouch is filled with peppermint candy. [It's poisonous.]",
    420: "You and your Target's mouth are filled with both sugar and spice.",
    421: "You and your Target grown an outtageously long gtay beard.",
    422: "You gain a Green Potion! [Grants a Wild Magic Roll.]",
    423: "You gain a Blue Potion! [Inflicts a Random Curse (pg. 21)on Drinker.]",
    424: "You gain a Red Potion! [ Cures all wounds and Curses.]",
    425: "You gain a Grey Potion! [Reduces HP to 1.]",
    426: "You gain a Yellow Potion! [Resurrects a corpse, or gives you the runs.]",
    427: "You gain a Clear Potion! [It's just water.]",
    428: "You alter your fate, changing one physical attibute about you.",
    429: "Your Target doesn't believe you are real.",
    430: "You don't believe your Target is real.",
    431: "Your Target no longer believes magic is real or can harm them.",
    432: "You no longer believe magic is real or can harm you for the next 48 hours.",
    433: "For the next turn, no one on the field believes magic isreal or can harm them.",
    434: "For the next turn, magic is not real and cannot harm anyone.",
    435: "The nearest building is turned into a ginger bread candy house.",
    436: "A portal to the nearest friendly town opens beside you.",
    437: "A portal to your childhood home opens beside you.",
    438: "A portal to the cruel vacuum of space opens beside you.",
    439: "Your Target gains a big purple pointy hat. It confers +1 WIS and +1 INT.",
    440: "Customize your and your Target's eyes!",
    441: "You or your Target are invincible until the end of your next turn. Flip a coin to see who.",
    442: "You or your Target deal double DMG on your next turn. Flip a coin to see who.",
    443: "You or your Target get an immediate see Turt. Flip a coin to see who.",
    444: "Your most read book in your possession gains sentience and telepathy. If it is a magical tome, it can cast some magic.",
    445: "You gain a big blue pointy hat in your inventort. [It applies a random Curse to the first 3 people to wear it.]",
    446: "You ttansfort into a mimic chest for the next 24 hours.",
    447: "All your coins now talk.",
    448: "All your armor and equipment is teleported to a chest that appears beside your Target. The chest is thankfully unlocked.",
    449: "All your Target's armor and equipment is teleported to a chest that appears beside you. It's locked and they have the key",
    450: "Surprise Birthday Party!",
    451: "All your copper is transformed to gold!",
    452: "All your gold is transformed to… copper…",
    453: "All your coins now have a distinctive rainbow coloration. This potentially could increase their value, or devalue them entirely.",
    454: "Your Target's boots turn to solid gold. If they did not have boots they now gain solid gold boots.",
    455: "A murky darkness appears above your head. You may ask it one question. (You can only answer with Magic Eight Ball responses; ex “It is certain”, “Outlook not so good”, or “Ask again later.”)",
    456: "The Aether reveals one detail about your future. [Should this not come to pass, something cataclysmic will happen as the Aether attempts to adjust.]",
    457: "You and your Target switch noses for the next hour.",
    458: "You and your Target switch arms and hands for the next hour. This includes whatever you were holding.",
    459: "You and your Target switch legs for the next hour.",
    460: "You and your Target switch voices for the next 24 hours.",
    461: "Perform the action that caused the Wild Magic again at no cost. If it kills your Target you can also perform the Wild Magic again.",
    462: "A church bell imp is ripped through the Aether and onto the field. He's playing the 1812 Overture perfectly with just a church bell. But also holy shit it's really loud.",
    463: "All books on the field become sentient, grow teeth and are ravenous. They are next in initiative queue. (This effect ends in 30 minutes.)",
    464: "Right here, right now you can choose to teleport anywhere through the Aether. (When a location is chosen, flip a coin to see if they hit something.)",
    465: "Your Target gains the ability to teleport anywhere on the field instead of moving. [This is caused by a magical gland they just grew.]",
    466: "You gain a plague doctor's full attire.",
    467: "You and your Target swap all hair.",
    468: "You and your Target switch bodies for 1 Turn each.",
    469: "A random Party Member is now tagged as “It”. [Refer to Tag rules when determining how Players can remove the “It” Status Effect.]",
    470: "You are now covered in leeches. [They heal the Caster 2d4 DMG for the next 3 turns or until they die or are removed.]",
    471: "Disco Ball lighting.",
    472: "You've gained an addiction to phonics.",
    473: "You immediately become elderly, but will never age again.",
    474: "Your Target immediately becomes elderly, but will never age again.",
    475: "You and your Target's most powerful possessions are teleported into a chest between the two of you. [Whoever opens the chest gains a Random Curse (pg. 21) but also gets to claim both items.]",
    476: "You gain a massive talking boil on your cheek. +1 WIS!",
    477: "Sentient Hand.",
    478: "Your hand has a mouth that can consume the power of evil spirits.",
    479: "You're a wizard now.",
    480: "You decide it's time to retire.",
    481: "You Target decides it's time to retire.",
    482: "A mascot grants you the power to be a magical girl.",
    483: "You gain the most valuable tome of knowledge that will ever be known… It's empty as it hasn't been written yet.",
    484: "An angelic envoy is ripped through the Aether and appears beside your Target. Flip a coin to see who will hear its message. [Hearing the message deals 2d10 DMG, but also gains the favor of the angel.]",
    485: "You are marked for death as parm of the ritual end of your realm.",
    486: "Your Target is marked for death as parm of the ritual end of their realm.",
    487: "You gain a set of 10 magical unbreakable nails.",
    488: "An Opportunity.",
    489: "You gain magical tattoos that channel arcane power. +2 WIS!",
    490: "Your Target gains magical tattoos that channel arcane power. +2 WIS!",
    491: "You gain a jar of healing leeches.",
    492: "You are briefly brought to a blue velvet room and must draw a tarot card. This card expresses a parm of your true self which you can unleash as an attack once you have fully come to terms with it.",
    493: "You reshuffle your deck and may look at your top 3 cards. Gain advantage for the next 3 rolls.",
    494: "You mill your opponent and deal 3d10 DMG.",
    495: "You untap all lands and gain an extra turn.",
    496: "Your Target monologues about their entire master plan, giving away at least one secret. They also gain advantage on their next 3 rolls.",
    497: "You were into this Wild Magic Table before it was cool. Cast any Spell below 9th level for free and instantly. Thanks for your support!",
    498: "Cast a spell that you totally just made up and doesn't completely alter reality. (ex: You can't cast Legally Distinct Wish.) [This Spell is learned by the Target immediately.]",
    499: "A mountain of magical texts drops on your target dealing 5d100 DMG. Only d6 of the tomes are actually useful.",

};

const umbralRole = {
    500: "Your Target is invisible forever now.",
    501: "You can't see for the next 24 hours.",
    502: "You are now colorblind.",
    503: "Your Target can't see for the next hour.",
    504: "All light sources within a mile go out.",
    505: "Your Target falls asleep.",
    506: "Everyone on the field (except you and your Target) fall asleep for one turn.",
    507: "Someone, somewhere misses work because of you. And that's very bad.",
    508: "The goes out for 10 minutes causing frost and darkness across the planet.",
    509: "You move silently for the next 24 hours.",
    510: "You can see through all darkness, magical and non-magical, for the next 24 hours.",
    511: "You can see through all darkness, magical and non-magical. Light really hurts your eyes though.",
    512: "All your clothes are died black.",
    513: "All clothes on the field are died black.",
    514: "You gain a bleak outlook on life and enjoy listening to sad music much more than you used to.",
    515: "You fall into a deep sleep, only magic or true love's kiss can wake you now…",
    516: "The ground on the field becomes an inky black goo and is now difficult terrain.",
    517: "Your pockets overflow with caltrops.",
    518: "A mysterious sniper takes a shot at your target from the shadows dealing 2d10 DMG.",
    519: "A mysterious sniper takes a shot at you from the shadows dealing 2d10 DMG.",
    520: "You teleport to any shadow you can see.",
    521: "A thick fog fills the air.",
    522: "A thick fog fills the air… You realize it's actually hot steam and everyone is a bit wet now.",
    523: "You gain a bottle of foggy weather.",
    524: "You summon a shadow clone of yourself beside you, it will obey your every command but cannot fight. It will dissipate when exposed to sunlight.",
    525: "Your Target's shadow leaps into the fight to aid them. [Sunlight or the Target's death are the only things capable of harming it.]",
    526: "A talking crow companion is ripped from the Aether and appears on your shoulder.",
    527: "A talking crow is ripped through the Aether and pissed at you for bringing it here. It attempts to peck out your eyes.",
    528: "You permanently look and sound sleepy.",
    529: "You gain chocolate so dark, it absorbs all light within 10' of it.",
    530: "Your Target can't speak or make noise for 2 hours.",
    531: "You can now only speak to your Party Members.",
    532: "You gain a mysterious but alluring aroma.",
    533: "Your Target gains chronic and acute depression.",
    534: "You are afflicted by kleptomania for 24 hours.",
    535: "No one trusts your Target for the next 24 hours.",
    536: "You can only tell lies for the next hour.",
    537: "Your Target can only tell lies for the next hour.",
    538: "You are seriously afraid of the dark.",
    539: "Your Target is seriously afraid of the dark.",
    540: "A bat appears in your mouth.",
    541: "A bat is ripped from the Aether and hits your target for 2d4 DMG. Flip a coin to see if the bat survives the impact.",
    542: "Your pockets are full of melted dark chocolate.",
    543: "You are completely hidden in a hay bail that appears on the field.",
    544: "You are completely hidden sitting on a bench that appears on the field.",
    545: "You can detect magic via sent for the next week.",
    546: "You vomit out a smoke bomb that goes off.",
    547: "Your target vomits out inky black goo. It's alive?",
    548: "You expertly dodge roll out of the way of the next Attack that targets you.",
    549: "You gain a cloak and a dagger. Neither are remarkable in any particular way.",
    550: "Your target gains a blindfold… on them.",
    551: "A comcially large bomb is ripped from the Aether an appears between you and your Target. It will detonate at the end of your next Turn. [It deals 3d20 DMG to any units adjacent to it and is 3' wide.]",
    552: "Your amror fills with crow feathers.",
    553: "Your Target grows crow feathers all over.",
    554: "You eyes are now cat eyes. If you already had cat eyes, your eyes are now dog eyes.",
    555: "The time of day is shifted to midnight.",
    556: "You can perfectly throw your voice up to 50' for the next 24 hours.",
    557: "You can't stop recommending this one band you really like to your Target.",
    558: "Your Target turns into a fine Gothic painting. [If they were near death they remain like this. If not they burst through the painting to attack anyone who tries to touch it.]",
    559: "You gain a locket with a sand dial on it. [It counts down the time until the Caster's natural death.]",
    560: "You gain a locket with a skull on it. [It will curse whoever opens it.]",
    561: "You Target gains a locket with tear drop on it. [It will scream loudly whenever opened.]",
    562: "You and your Target get your nails painted black.",
    563: "The field is now lit with moody candle-light.",
    564: "You are now inside an elaborate blanket fort that lets in no light. The fort has 5 HP.",
    565: "You no longer feel comfortable holding eye contact with other people.",
    566: "The sky outside is covered with thick black cloud. It blocks all light for 48 hours.",
    567: "A portal to a realm of pure pitch blackness opens beside you for the next 3 Turns.",
    568: "You and your Target gain an unreasonably good romantic and physical chemistry.",
    569: "You sleep soundly. You now gain the benefits of a long rest from a short rest… and can never be woken up until you'd normally wake up.",
    570: "You gain a warm blanket. As a free action you can also give your Target a warm blanket.",
    571: "You consider the merits of pacifism.",
    572: "You can only whisper for the next 24 hours.",
    573: "Your Target can only speak in a whisper.",
    574: "Your whispers are now silent to all but your allies.",
    575: "Your target is covered in pitch.",
    576: "You and your party are covered in pitch.",
    577: "Your Target loses the will to fight until it is attacked or sufficiently provoked.",
    578: "The Target's purse is cut and money spills out onto the field.",
    579: "A random party member relives the worst memory of their life in vivid detail. Everyone on the field sees and experiences it.",
    580: "The Target relives the worst memory of their life in vivid detail. Everyone on the field sees and experiences it.",
    581: "All of your Target's wealth in solid assets are transferred to your pouch. [This will likely weigh the Caster down severely and potentially cause DMG.]",
    582: "All of your Target's wealth in liquid assets are now legally transferred into your possession. [The Caster will have to pay taxes where applicable.]",
    583: "Neither you nor your Target can ever see each other again. You're totally invisible to one another.",
    584: "A miniature black hole opens on the field for 5 seconds. Everyone must perform a check not to get sucked into oblivion.",
    585: "A 50' pit opens beneath your Target's feet.",
    586: "A 50' pit opens beneath your feet.",
    587: "You fail all stealth checks for the next 24 hours because your dice rolling is too loud.",
    588: "Your Target's allies betray them.",
    589: "You think now would be the best time to betray your allies, and get a Natural 20 on your first act of betrayal should you choose to do it.",
    590: "You go prone and can't stand up (for fear of being spotted) for 2 hours.",
    591: "Your Target crouches and becomes invisible, they are now aware they have this power.",
    592: "You can speak with most rodents.",
    593: "You gain a small group of loyal rats who are also professional thieves.",
    594: "You gain a small group of loyal rats who are also professional chefs.",
    595: "Whenever you fail a stealth roll, flip a coin. If you win there were also rats running by you which distract whoever you were sneaking next to.",
    596: "Only your allies can recognize your face.",
    597: "A murder of crows are ripped through the Aether and appear beside your Target. They now head your Target's every word.",
    598: "You gain a Cardboard Box that gives you a +5 to all Stealth Rolls while you're inside it.",
    599: "Your Target is stabbed in the back by 5 different assassins at once. The Target takes 5d20 DMG before the assassins retreat.",

};

const verdantEruption = {
    600: "Any Undead with less than 20 health on the field are resurrected as their original living selves.",
    601: "Your Target is covered in vines and cannot move.",
    602: "Your Target is covered in poison ivy and cannot move. [The rash lasts for 3 days.]",
    603: "You are covered in poison ivy and cannot move. [The rash lasts for 3 days.]",
    604: "Your Target turns into a mighty and proud tree.",
    605: "A tree is ripped through the Aether and appears in front of you. The tree is 40' tall and 5' wide.",
    606: "Your hands are covered in tree sap, causing Disadvantage on all Rolls for the next hour.",
    607: "Your Target is covered in tree sap, causing them Disadvantage on all Rolls for the next hour.",
    608: "You smell like mint.",
    609: "You smell like a durian.",
    610: "Your pouch is filled with assorted fresh fruits.",
    611: "Your pouch is filled with assorted rotting veggies.",
    612: "Your pouch is filled with assorted gourds, slowing your movement by 2.",
    613: "A gourd is ripped through the Aether and dropped on your Target's head, causing 2d4 DMG and obscuring their vision for 1 Turn.",
    614: "You and your Target's weapons are covered in moss.",
    615: "You and your Target's weapons are covered in a deadly black mold.",
    616: "Your spit is now poisonous.",
    617: "Your spit is now venomous.",
    618: "A 5'x5' pit of acid appears behind your Target.",
    619: "You become completely hidden in a pile of leaves. Flip a coin to see if a squirrel with rabies is in here with you.",
    620: "All flora on the field becomes sentient and can speak telepathically for the next hour. The volume of their voices is proportional to their size.",
    621: "You and your Target are covered in bees causing 2d4 DMG to each of you.",
    622: "The field is filled with bees causing 2d4 DMG to anyone who moves. The bees persist for until dealt with or until 3 Turns have passed.",
    623: "You can now speak to rocks! You can't understand them back though… yet.",
    624: "The rocks can speak to you! You can't speak to them back though… yet.",
    625: "Your Target's blood turns into a fast-acting poison. Ironically they'll likely die due to lack of oxygen from the blood loss, not the poison. If they have no blood, they are now coated in a fast-acting poison. Best not to touch it.",
    626: "A gorilla is ripped through the Aether and appears beside you. Flip a coin to see if it's friendly.",
    627: "You gain Rancor giving you +2/+0 and Trample for 3 Turns. [Trample means any extra DMG you do to a Target after their demise now hits the nearest Target.]",
    628: "Turn into whichever bug you want for the next 2 turns. Max bug size is 10' by 10'. Water-bears are allowed.",
    629: "Transform into an elephant for 3 Turns.",
    630: "You and your Target's pockets are full of leaves.",
    631: "All your physical wounds heal. All your emotional wounds are then converted into d4 DMG.",
    632: "All your Target's wounds heal. If they are Undead they take DMG equal to what would've been healed.",
    633: "You have 30 seconds to decide someone you'd like to bring back from the dead. [Start counting down now.]",
    634: "A soothing aria washes over you, healing 2d10 DMG.",
    635: "You and your Target inhale hallucinogenic spores and are tripping balls for 1d4 Turns.",
    636: "Your Target becomes instantly sober. If they were not under the influence of anything before, they are now incredibly drunk or tripping balls.",
    637: "A cactus is now sticking you and your Target together. Causes 2d4 DMG when you pull off of or it's pressed in.",
    638: "You gain a small potted succulent. Gain +1 to any Rolls to protect it.",
    639: "You can speak with plants for 24 hours.",
    640: "A large legally distinct sentient cactus is ripped from the Aether and appears in front of you. Its goals an enigma.",
    641: "You can understand plants, but you can't speak back to them… yet.",
    642: "You can speak to plants, but you can't understand what they say back… yet.",
    643: "Your mouth is full of eggs.",
    644: "Your Target's blood now glitters.",
    645: "Your Target is pelted with eggs ripped from the Aether dealing d12 DMG.",
    646: "The field is covered in egg shells.",
    647: "Your Target's mouth is full of eggs.",
    648: "Your Target vomits out a flock of friendly doves.",
    649: "Your Target becomes an ecoterrorist.",
    650: "Everything on the field is coated in glitter.",
    651: "Your pockets are full of glitter.",
    652: "Your Target is covered in glitter. It'll be impossible to get all of it out of their clothes.",
    653: "An owl companion is ripped from the Aether and lands on your shoulder. It can share its vision to you.",
    654: "A violent owl is ripped from the Aether and lands on you.",
    655: "An Owlbear is ripped from the Aether and is dropped on your Target causing 3d4 DMG.",
    656: "A group of lawyers storm the field and serve you a cease and desist order from “WotC”. They inform you that no one (in or out of games) is allowed to say the words “Beholder”, “Carrion Crawler”, “Displacer Beast”, “Githyanki and Githzerai”, “Mind Flayer”, “Umber Hulk”, “Slaad” and “Yuan-Ti”. Failure to comply will result in lengthy legal proceedings.",
    657: "You and your Target gain a sinus infection.",
    658: "You lay an egg. What could be inside?",
    659: "Your Target lays an egg. What could be inside?",
    660: "You and your Target are cured of all illnesses.",
    661: "Your Target gains a highly contagious illness known as Fairy Flu. It causes you to lie and sneeze a lot.",
    662: "Your Target vomits out a rainbow. This heals any unit in front of it 2d4 DMG.",
    663: "Your pockets and bag radiate with a bright rainbow energy whenever you open them.",
    664: "You learn a new instrument!",
    665: "A group of fairies are ripped from the Aether and help you fly for the rest of combat.",
    666: "A group of fairies are ripped from the Aether and will continue to play pranks on you until they're dealt with.",
    667: "You owe a debt to a fairy queen.",
    668: "You gain a fairy companion who explains the obvious.",
    669: "You take up yoga and gain +1 Speed.",
    670: "You and your Target get very hot and bothered.",
    671: "No matter how much either of you bathe, you and your Target always smell like a mix of your body odors.",
    672: "A fairy is ripped from the Aether and gives a Random Curse (pg. 21) to both you and your Target.",
    673: "You and your Target are now allergic to each other.",
    674: "Your target is afflicted by terrible allergies for 24 hours.",
    675: "You are afflicted with terrible allergies for 24 hours.",
    676: "The time of day is shifted to high noon.",
    677: "You gain 5 years of hair growth everywhere.",
    678: "You transform into a bear for the next hour.",
    679: "Somehow, somewhere a bear transforms into you for the next 24 hours. [There will likely be consequences…]",
    680: "You transform into a poison dart frog for the next hour.",
    681: "You turn into whatever creature your Target is for the next 24 hours. You now know its language.",
    682: "Your Target turns into whatever creature you are for the next 72 hours. It now knows your language.",
    683: "Your Maximum HP is increased by d20.",
    684: "Your Target's Maximum HP is increased by 2d20",
    685: "For the next 12 hours you can see exactly how many hit points your opponents have left.",
    686: "You and your target have a long, but needed talk. Even if you don't see eye to eye, you get to know each other and yourselves better… at the cost of 2d4 DMG each.",
    687: "A swarm of friendly bees are ripped from the Aether to your side. They'll follow your lead… mostly.",
    688: "There's a frog friend who lives in your bag now.",
    689: "D100 harmless snakes erupt from your hand.",
    690: "You and your Targets' body hair is replaced with leaves.",
    691: "Your Target finds themselves on top of a hungry raptor.",
    692: "You find yourself on top of a very hungry raptor.",
    693: "Your Target is covered in flowers.",
    694: "You and your Target's mouths are filled with flower petals or every shape and color.",
    695: "You gain bee wings for an hour and can fly.",
    696: "Your Target gains permanent bee wings and can fly.",
    697: "Your Target is the size of a mouse but gains double HP and double DMG until the end of your next turn.",
    698: "A tree falls in the woods and somehow hits your Target for 2d10 DMG. It does not make a sound.",
    699: "Your target is assailed by rabid squirrels that storm the field, causing 5d20 DMG.",
    
};


const undyingChance = {
    700: "You die on the spot. You are immediately brought back to life with all your previous health! You are however now an undead.",
    701: "Your arm is rotting off until you seek medical aid.",
    702: "Your Target’s arm is rotting off. It’s nasty.",
    703: "You crave the flesh of the living for 24 hours.",
    704: "Your Target craves the flesh of the living for 24 hours.",
    705: "Your Target contracts the bubonic plague.",
    706: "You can now drink the blood of the living to restore 2d4 HP.",
    707: "Your Target becomes an undead ghoul. If they were already an undead ghoul, they become a corporate ghoul.",
    708: "Your Target becomes an undead skeleton. If they were already a Skeleton, they inexplicably gain more bones. More skeleton!",
    709: "A skeleton playing a trombone is ripped through the Aether and hits you and your Target for 3d4 DMG each.",
    710: "Your armor is now ornamented with twisted and broken bones.",
    711: "Your Target’s armor is now ornamented with the remains of your dead loved ones. Ouch.",
    712: "The field is now covered in broken bones and mangled corpses, becoming difficult terrain.",
    713: "Every plant smaller than you that you touch, dies, for the next 24 hours.",
    714: "A pile of rotting corpses drops on your Target dealing d20 DMG.",
    715: "A pile of rotting corpses drops on a random ally, covering them completely, but shielding them from harm until their next turn.",
    716: "You've contracted scarlet fever.",
    717: "You gain a talking skull. [It's smart but sassy.]",
    718: "You can speak with bones for the next 24 hours.",
    719: "You can understand what bones whisper, but you can't speak back to them…yet.",
    720: "You can whisper to the bones, but they have no way to whisper back to you…yet.",
    721: "You become a skeleton for 24 hours.",
    722: "You literally always look like you're dying.",
    723: "You contract a mild flu. It is contagious,",
    724: "Your Target has a very runny nose.",
    725: "You are swarmed by rats and take 2d4 DMG each turn until you give them something to eat.",
    726: "Your pockets are full of plague rats.",
    727: "Your Target's pockets are full of plague rats.",
    728: "You are covered in your Target's blood. They take 2d4 DMG.",
    729: "Your Target is covered in your blood, You take 2d4 DMG.",
    730: "The field and everyone on it is drenched in blood.",
    731: "Your breath is horrible for the next week.,1CHA.",
    732: "You or your Target's teeth rot. Flip a coin to see who.",
    733: "You or your Target throw out your back. Flip a coin to see who.",
    734: "Your weapons are coated in poison for the next 2 hours.",
    735: "Your Target's weapon is imbued to always be dripping poison.",
    736: "A passive poison dart frog is ripped from the Aether and appears between you and Target.",
    737: "You feel the need to defend cannibalism.",
    738: "Your Target takes up cannibalism.",
    739: "You gain sharp fangs.",
    740: "No spines, only victory.",
    741: "You gain a bloody nose. Flip a coin tosee if it's your nose bleeding or your Target's nose in your hand.",
    742: "You and your Target dance uncontrollably to one of a myriad of overplayed horror-themed dance routines (ex: Monster Mash, Time Warp,SpookyScarySkeletons) until your next turn.",
    743: "You gain the relative knowledge of a lich for 1 hour.",
    744: "The souls of your Target's dead allies will forever haunt them.",
    745: "You are haunted by every life you've taken until the end of the encounter. This causes Disadvantage and other mayhem.",
    746: "Your Target is haunted by every life they've taken for 2d4 Turns. This causes Disadvantage and other mayhem.",
    747: "A random living thing on the field is turned undead.",
    748: "You are resurrected! If you were not dying, take 2d20 DMG.",
    749: "You gain a talking skeleton key.",
    750: "Your weapon turns to dark chocolate for 2 turns.",
    751: "You gain a Jack O'Lantern helmet.",
    752: "You and your Target are covered in undead spiders. Make a check to see if you can shake them off, or become were-spiders.",
    753: "You age by 30 years.",
    754: "Your Target ages by 30 years.",
    755: "A random unit on the field ages by 30 years.",
    756: "All units on the field are reduced to 1 HP until your next turn. At that point all conscious units' HP is restored to its previous State.",
    757: "Undead ignore you and see you as one of their own for 24 hours.",
    758: "Undead see you as particularly tasty and will prioritize attacking you for 24 hours.",
    759: "You gain a sheet over your head with eye slits. While wearing the sheet, units must make a Save or see you as a ghost.",
    760: "Your Target gains a ghostly aura and rotting flesh.",
    761: "All of the consumables in your pouch spoil.",
    762: "All the consumables in a 30' radius spoil.",
    763: "Your Target is covered in maggots.",
    764: "You are covered in flies.",
    765: "The tombstone of a loved one is ripped from the Aether and hits your Target for 2d20 DMG.",
    766: "You and your Target now have bones that can never break.",
    767: "A bone is ripped from the Aether and hits your Target for2d10 DMG. [If anyone makes a joke about the Target “getting boned”, another bone is ripped from the Aetherand hits that person for 2d10 DMG.]",
    768: "Your limbs are barely held together by stitches. [The limbs still function and heed their brain's command when separated.",
    769: "Your Target's limbs are barely held together by stitches. [The limbs still function and heed their brain's command when separated.]",
    770: "Plastic replicas of both you and your Target's skeleton are now riding on top of your respective backs.",
    771: "You are buried alive in a coffin 6' beneath your current position. Everyone on the field knows this.",
    772: "Your Target is buried alive in a coffin 6' beneath their current position. Everyone on the field knows this.",
    773: "You gain a xylophone made of bones! [Once per combat it can be played to grant a random party member inspiration.]",
    774: "Your bones are now technically made of spaghetti, but otherwise perfectly functional.",
    775: "You can “go ghost” for the next 2 hours, allowing you to pass through walls, but also drawing a great deal of attention from paranormal forces.",
    776: "Your spit is now corrosive.",
    777: "Your Target's spit is now corrosive.",
    778: "You gain the deed to a haunted decrepit manor on a cliff side.",
    779: "Everything metal on the field rusts.",
    780: "All of your Target's teeth fall out in perfect condition.",
    781: "A random party member is now being followed by the seemingly benign ghost of a gibbon.",
    782: "You stain your favorite item.",
    783: "Explodey Bones.",
    784: "You gain the deed to a very full graveyard.",
    785: "You become hideous in a deeply hot and attractive way. +1 CHA.",
    786: "Your great love dies of cholera. Or is broughtback from the dead.",
    787: "You gain an undead version of a prior pet or mount. If you don't have a prior pet or mount, gain either an undead cat, dog, small reptile,small bug or small bird.",
    788: "Gain a bag of poison. Like a potato sack, it's dripping everywhere.",
    789: "A random party member is covered indead flowers.",
    790: "Endless meatbag.",
    791: "Endless bone bag.",
    792: "Endless blood bag.",
    793: "Your Target gains an army of undead soldiers. They're not here, but if the Target escapes or survives, they can command them.",
    794: "Your body falls to the ground and you possess your Target as a ghost for 1d4 Turns. Harming yourself will require passing checks.",
    795: "You gain an insatiable hunger for your Target's flesh. Gain advantage when attacking them if you're aiming to kill. You must consume them when they're dead.",
    796: "Your Target is now the last living member of their bloodline, excluding any relatives on the field.",
    797: "One of your eyes falls out and is replaced with a glass “ghost eye” which can see ghosts plainly.",
    798: "Your Target now gains the powers of anyone they eat,and they are acutely aware of this ability.",
    799: "A giant skeleton erupts from a portal and smacks your target for 5d20 DMG before dabbing and retreating from the field.",
};

const elderCalling = {
    800: "You realize you are a fictional character in the collective mind of human players. This brief, horrifying enlightenment allows you to choose what you roll next turn.",
    801: "You see beyond the stars and time, to the cold dead end which awaits all of eternity. +1 WIS! You're scarred for life now!",
    802: "The [The first Player to say “what” vomits a swarm of cockroaches that will devour the nearest d8 consumables.]",
    803: "Lawyers representing “WotC” send a private message to your GM. You know that the GM is under investigation if they are playing the 5th Edition of a certain rule system without using preapproved and purchased material. If there is any “homebrew”, the GM is fined for 10,000 USD for damages or must host a pizza party in the name of “WotC” and “IP” for the players at the table.",
    804: "You can speak with the stars for 24 hours.",
    805: "You can speak to the stars, but they can't speak back… yet.",
    806: "You can understand what the stars speak to you, but you can't communicate back to them… yet.",
    807: "Your mouth is full of loose eyeballs.",
    808: "Your Target's mouth grows a number of eyeballs inside.",
    809: "You are bathed in cosmic dust and glow with a sickening resplendence for 5d20 hours.",
    810: "Your pouch is full of loose eyeballs.",
    811: "A crazed lycanthrope is ripped from the Aether and appears on the field between you and your Target. The next unit it successfully attacks will gain lycanthropy.",
    812: "You accept you cannot change the past and are overcome with the fear that you cannot change the future.",
    813: "You can change one thing that happened in the past 24 hours.",
    814: "Your pouch is filled with books in an alien script, halving speed.",
    815: "Your Target vanishes until your next Turn. No one but you remembers your Target existing until they return.",
    816: "Your Target is being abducted by extraterrestrial life.",
    817: "You and a random party member are being abducted by extraterrestrial life.",
    818: "The field is covered in rust and a staticy noise.",
    819: "A distant scream fills the room, filling everyone with dread. Everyone on the field gets,3 on their next roll.",
    820: "You use your next turn to scream in madness and fear.",
    821: "Your Target takes their next turn to scream in madness and fear.",
    822: "You can't understand any language until your next turn, as your mind is briefly opened to the language of the cosmos.",
    823: "Your mouth bleeds as an ancient force speaks through you, causing 2d10 DMG to any who hear its summons.",
    824: "You can't blink for the next 24 hours.",
    825: "Your Target can't blink for the next 24 hours.",
    826: "You have this terrible feeling you're forgetting something.",
    827: "A carbon copy of your Target's mind is safely implanted within your mind for the next 24 hours, allowing you to hear their thoughts constantly, even after death.",
    828: "Your brain is now in a jar in your pouch. It can remotely communicate with your body from up to a mile away.",
    829: "You are covered in eldritch bile granting you all thinkable elemental resistances for the next 3 Turns.",
    830: "An eldritch being briefly notices the field, causing gravity to feel looser and objects to float.",
    831: "An eldritch being briefly notices the field, causing a random creature within to gain a Random Curse (pg. 21).",
    832: "An eldritch being briefly notices the field, causing a brief pause in the fight to renegotiate before rerolling initiative.",
    833: "You or your Target's eyes are bleeding, causing blindness for 1 Turn. Flip a coin to see who.",
    834: "You and your Target's eyes are bleeding, causing blindness for d4 turns. [Anyone else who touches the blood is dealt 3d4 DMG.]",
    835: "You mumble an ancient name and any holy symbol within 30' of you shatters permanently.",
    836: "You mumble an ancient name and any unholy symbol within 30' of you shatters permanently.",
    837: "A group of omnipotent demi-beings listen to their proctor read off the results of a dice roll and contemplate the consequences.",
    838: "An eldritch being offers you a deal: It'll wipe away your Target in exchange for a Soul Debt.",
    839: "A Soul Debt to an eldritch being has been passed to you.",
    840: "A distant relative has passed away. An invitation has been sent for you and your party to come to their mansion to hear the reading of their will. It hits your Target for d4 DMG.",
    841: "Gravity gets heavier making every physical action harder and causing localize havoc for the next 3 Turns.",
    842: "Your head size is doubled for an hour.",
    843: "Your Target's head size is doubled for an hour.",
    844: "A random unit on the field gets the ability to summon 2d4 tentacles from their back at the cost of 2d4 HP.",
    845: "An eldritch being puts you and your Target in the time-out corner until your next turn. You cannot fight here.",
    846: "Everything you say sounds like gibberish for d4 hours.",
    847: "Everything your Target says sounds like gibberish for d4 hours.",
    848: "Time becomes convoluted. Everyone reroll initiative.",
    849: "It begins raining blood outside for the next d4 days.",
    850: "It begins raining emerald tears outside for the next d4 days",
    851: "You gain a third eye.",
    852: "You gain a second tongue.",
    853: "You gain two more ears.",
    854: "You or your Target's left and right hands are switched. Flip a coin to see who.",
    855: "You or your Target has your skin turned inside out for d10 Turns. Flip a coin to see who.",
    856: "You or your Target now have unbreakable emerald nails. Flip a coin to see who.",
    857: "You and your Target now bleed emerald blood.",
    858: "An Eldritch being borrows your weapon briefly, and will return it on your next turn. [It will be covered in toxic goo and sprouting eyeballs. The weapon is now somewhat sentient.]",
    859: "An Eldritch being will whisper a riddle of the future to you soon.",
    860: "Time stops for everything except sentient unit on the field. This continues until the encounter ends.",
    861: "Confetti drops on you and your Target, accompanied by a sudden pop and the sound of party blowers.",
    862: "Ants in your pants.",
    863: "For the next d6 hours you can move through any living creature.",
    864: "For the next 2d20 hours you can see through your Target's eyes.",
    865: "Your lymph nodes swell and you vomit a terrible blue bile, dealing 2d10 acid DMG to anything withing 15' of you.",
    866: "The housing market crashes.",
    867: "What appears to be a version of you from the future appears beside you. They deal 3d20 DMG to your Target and say there's no time to explain. They then ask you to lend them all of your money. They will not leave until you pay them or deal with them.",
    868: "A set of runic handcuffs now bind you and your Target. [The cuffs will only release through the casting of powerful magic or after a week has passed.]",
    869: "You download a car.",
    870: "You gain a teddy bear that can hold d4 souls.",
    871: "You gain a sentient teddy bear that chitters eldritch secrets with its human-looking teeth.",
    872: "You gain an elixir of holy healing blood. It's bottomless, but is said to drive the drinker slowly mad.",
    873: "The GM asks you to reiterate what you rolled. [Loop to taste.]",
    874: "Chance smiles on you and grants 2 immediate Wild Magic Rolls.",
    875: "You gain a crystal from a dying star.",
    876: "Your Target begins bleeding from every orifice.",
    877: "Everyone gains party blowers in their mouths.",
    878: "Three left hands.",
    879: "An demi-being hosts you and your Target to an underwhelming pizza party. You are both now in its debt.",
    880: "You hit your Target so hard they are slightly cooked by the force of the kinetic impact.",
    881: "Down is up. Up is down. [Uninvert in 2d4 Turns.]",
    882: "You and your Target are constipated for the next 4d4 days.",
    883: "You and your Target are now blood related.",
    884: "Cheese doesn't sit as well with you and your Target as it used to.",
    885: "Your Target is replaced with a version of them from an alternate reality. This version is much kinder.",
    886: "Your Target is replaced with a version of them from an alternate reality. This version is much crueler.",
    887: "Your Target is replaced with a version of them from an alternate reality. This version is more advanced.",
    888: "Your Target is replaced with a version of them from an alternate reality. This version is more primordial.",
    889: "You and your Target become vegan.",
    890: "You can read any written text in any language for 2d4 days.",
    891: "Your Target is chosen as the champion of an demi-being. If they're not defeated they will usher in the end of the universe.",
    892: "??? [Upon defeat the Target gains an extra final form semiangelic form and attempts to end the world.]",
    893: "Ray Gun.",
    894: "If the moon is visible you transform into an unstoppable monster for the rest of the encounter.",
    895: "If the moon is visible your Target explodes into gore, permanently turning the moon red. [Consequences to follow…]",
    896: "All the teeth you've collected turn into unknowable priceless alien gemstones that can be used in crafting.",
    897: "Free Real Estate.",
    898: "You begin the end of the cosmos by awakening the Sleeping One. Thankfully it'll take 300 years for it to properly awaken, so it's probably not your problem.",
    899: "You speak the name of the Unspeakable One. Your tongue twists and snaps and bleeds as you utter its horrible vowels. Your Target then takes 8d20 DMG.",
    }
    

    const hundredRandomCurses = {
        0: "You have no idea what this curse does. You're pretty sure it's one of the worst curses a person could think of. [This curse takes the form of whatever someone at the table thinks the curse is.]",
        1: "You are turned to stone.",
        2: "You are turned to gold.",
        3: "You are turned to glass.",
        4: "You cannot distinguish faces.",
        5: "You take d4 DMG whenever you speak.",
        6: "You take d4 DMG whenever you hear a name.",
        7: "You trust everyone.",
        8: "You smell horrible to everything.",
        9: "You have no sense of direction, ever.",
        10: "You trust no one.",
        11: "Your hands are always greasy.",
        12: "Your feet feel like bricks and your movement is halved.",
        13: "Whenever you speak you say the opposite of what you mean.",
        14: "Whenever you speak it sounds like a whisper.",
        15: "Everything you try to eat turns to gold.",
        16: "Everything you try to eat turns to ash.",
        17: "Everything you try to eat turns to nutritious worms.",
        18: "Everything you try to drink turns to strong wine.",
        19: "Your footsteps are slimey.",
        20: "Your footsteps make clown shoe noises.",
        21: "You can't see in the light.",
        22: "Everything you cook comes out burnt.",
        23: "You owe a debt to a devil.",
        24: "You owe a debt to a lich.",
        25: "You owe a debt to a dragon.",
        26: "You owe a debt to a crime lord.",
        27: "A fairy now owns your name and collects royalties from you whenever it is said in the amount of 4d4 copper.",
        28: "Your blood is cold and can't be warmed up.",
        29: "You suffer constant hot flashes.",
        30: "You have an allergy to dairy.",
        31: "You have an allergy to tomatoes.",
        32: "You have an allergy to animal fur.",
        33: "You have an allergy to magic. [Grants +3 on Detect Magic rolls.]",
        34: "You have a crippling fear of blood.",
        35: "You feel a shadow constantly stalking you.",
        36: "You never age, but rather you now have a painting that ages in your stead. [Caster dies if the painting is destroyed.]",
        37: "You longer float in water. Instead you sink, fast.",
        38: "You are turned into a cow.",
        39: "You are turned into a newt.",
        40: "You are turned into an owl.",
        41: "??? [Every spell they cast fails spectacularly.]",
        42: "??? [Every spell they cast hits you and you alone.]",
        43: "??? [Spell casting costs are doubled for them.]",
        44: "You can no longer spell.",
        45: "You can no longer read.",
        46: "Your hair is infested with tiny biting spiders that somehow always repopulate when you think you're rid of them.",
        47: "Your clothes are always moldy.",
        48: "Your first born is or will be turned into a toad.",
        49: "You turn into a werewolf under the full moon.",
        50: "You turn into a small dog under the full moon.",
        51: "When angry, an insatiable blood lust is awoken inside you.",
        52: "You can never remember names.",
        53: "You turn to living stone.",
        54: "You turn into a sentient tree.",
        55: "??? [Caster is struck by lightning for 2d10 DMG every time a party member says “Look out!” or issues similar warnings to them.]",
        56: "You vomit every time someone says your name in front of you.",
        57: "??? [The Caster passes out every time someone mentions or asks them about their curse.]",
        58: "You lose control of yourself while you sleep. [Caster commits awful deeds and even takes lives.]",
        59: "You lose control of yourself while you sleep. [You grind you teeth loudly enough to have a chance to wake up others.]",
        60: "You lose control of yourself while you sleep. [Caster collects acorns that you stow away under your bed.]",
        61: "You can no longer rest.",
        62: "You can no longer sleep for more than 2 hours at a time.",
        63: "You can longer wiled weapons effectively.",
        64: "Your hands are invisible.",
        65: "You are always seen as and called “short” or “tall” by others. Flip a coin to see which one.",
        66: "You are always called by the wrong name.",
        67: "You are always asked about your heritage.",
        68: "You must always move your full movement when moving.",
        69: "You are allergic to nuts. [Interpretive.]",
        70: "You are allergic to the undead.",
        71: "All the music you try to make sounds awful.",
        72: "You always feel high.",
        73: "You always feel drunk.",
        74: "You always feel like somebody's watching you.",
        75: "You will always get denied when requesting something.",
        76: "Every voice you hear sounds like your voice.",
        77: "You narrate everything you do. [Whatever the Player says is the Caster's narration.]",
        78: "You fall asleep when you health drops below 5 HP.",
        79: "You fall asleep when people tickle you.",
        80: "Your face is covered in markings that change each morning.",
        81: "You are always hungry.",
        82: "You are always thirsty.",
        83: "You are convinced you are a tortoise.",
        84: "You start coughing violently whenever you laugh, taking d4 DMG.",
        85: "You need to use the bathroom once every 2d4 hours, or you'll literally explode.",
        86: "You must remind your viewers to like and subscribe every time you do something cool, or take 3d20 DMG.",
        87: "You will never get a discount.",
        88: "When you sleep it is always for 8 hours and nothing can wake you.",
        89: "You age at triple the normal speed.",
        90: "You are destined to die in one month if this curse isn't lifted.",
        91: "You have terrible hand-eye coordination and suffer disadvantage on all attack rolls.",
        92: "You think every act of kindness is a trap.",
        93: "If you return to your home or hometown you'll combust into flames and take 2d20 DMG.",
        94: "Your stocks are always dropping.",
        95: "You can never find the other sock or glove.",
        96: "You must hide your face or deal an initial 2d10 DMG to anyone who witnesses it for the first time.",
        97: "A gremlin lives inside your pouch and is constantly stealingn random items and gold for its treasure horde.",
        98: "Your entire family forgets who you are and everything about you.",
        99: "Roll on this curse table 3 times. These three curses are counted as a singular combined mega-curse.",
        }


        const fantasyGenerator = [rawChaos, tidesOfChange, shockingLuck, pyromania, arcaneGamble, umbralRole, verdantEruption, undyingChance, elderCalling, hundredRandomCurses];

    function randomResult() {
        let finalResult = [];
        for (let i = 0; i < fantasyGenerator.length; i++) {
            let generator = fantasyGenerator[i];
            let keys = Object.keys(generator);
            let len = keys.length;
            let rnd = Math.floor(Math.random() * len);
            let roll = generator[keys[rnd]];
            finalResult.push(roll);
        }
        finalResult = finalResult.join("<br>");
        document.getElementById("generation-display").innerHTML = finalResult;
        
    }